Documents/Dsblog/dsblog/blog/urls.py
from django.urls import path
from . import views 


app_name = 'blog'

urlpatterns = [
    path('NewPost/', views.NewPost, name='NewPost'),
    path('post/<int:id>/detail/', views.post_detail, name='post_detail'),
    path('post_list/', views.post_list, name='post_list'),
    path('post/<int:id>/update/', views.update_view, name='update_view'),
    path('post/<int:id>/delete/', views.delete_view, name='delete_view'),
]

Documents/Dsblog/dsblog/dsblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

Documents/my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

note/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notepad.urls')),
    path('improvednote/', include('improved_note.urls')),
]

Documents/Dsblog/dsblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'),
                     ('published', 'Published'),
    )
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    #this is to send the user back to the detail page after the success of creating a new post
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.id])

Documents/Dsblog/dsblog/blog/forms.py
from .models import Post
from django.forms import ModelForm

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']

Documents/Dsblog/dsblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http  import HttpResponseRedirect
from .forms import PostForm
from .models import Post
# Create your views here.
def NewPost(request):
    template_name = 'NewPost.html'
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_obj = form.save(commit=False)
            post_obj.author=request.user
            post_obj.save()
            form.save()
            return HttpResponseRedirect(reverse('blog:post_list'))
    else: 
        form = PostForm()
        return render(request, template_name, {'form':form})

#this view is to obtain a single post
def post_detail(request, id):
    template_name = 'post_detail.html'
    post = get_object_or_404(Post, id=id)
    return render(request, template_name, {'post': post})

#this view is to obtain a list of our posts
def post_list(request):
    template_name='post_list.html'
    posts = Post.objects.all()
    return render(request, template_name, {'posts': posts})

#this view is for editing a post
def update_view(request, id):
    template_name = 'edit.html'
    body = {}
    obj = get_object_or_404(Post, id=id)
    form = PostForm(request.POST)
    if form.is_valid():
        post_obj = form.save(commit=False)
        post_obj.author=request.user
        post_obj.save()
        form.save()
        return HttpResponseRedirect(reverse('blog:post_list'))
    body['form'] = form
    return render(request, template_name, body)


# this view is to delete a post
def delete_view(request, id):
    template_name = 'delete.html'
    body = {}
    obj = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        obj.delete
        return HttpResponseRedirect('post')
    return render(request, template_name, body)

Documents/Dsblog/dsblog/blog/templates/NewPost.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

Documents/Dsblog/dsblog/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog.</p>
 </div>
 <div class="nav-right">
    <a href="{% url 'blog:NewPost' %}">** New Blog Post</a>
 </div>
</body>
</html

Documents/Dsblog/dsblog/blog/templates/delete.html
{% extends "base.html" %}
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you sure you want to delete post?
        <input type="submit", value="YES"/>
    </form>
</div>

Documents/Dsblog/dsblog/blog/templates/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit post</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Update">
    </form>
{% endblock content %}    

Documents/Dsblog/dsblog/blog/templates/post_detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
{% endblock %

Documents/Dsblog/dsblog/blog/templates/post_list.html
{% extends "base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}