Documents/Dsblog/dsblog/dsblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

Documents/my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

Documents/my_blog/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns= [
    #Homepage
    path('', views.homepage, name='homepage'),
    path('posts/', views.posts, name='posts'),
    path('new_post/', views.PostCreate, name='new_post'),
    #Editing posts
    path('edit/', views.EditPost, name='edit'),
]

note/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notepad.urls')),
    path('improvednote/', include('improved_note.urls')),
]

Documents/my_blog/posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    #published = PublishedManager()
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        
        if len(self.body)  > 50:
            return self.body[:50] + '...'

        else:
            return self.body

    class Meta:
        verbose_name_plural = 'articles'

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

Documents/my_blog/posts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Article

# Create your views here.

#to show homepage
def homepage(request):
    return render(request, 'posts/homepage.html')

#to show all posts we do this
def posts(request):
    posts = Article.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'posts/posts.html')

#to create a post
def PostCreate(request):
    return render(request, 'posts/new_post.html')

#to edit a post
def EditPost(request, article_id):
    """Edit an existing article."""
    article = Article.objects.get(id=article_id)
   
    if request.method != 'POST':
        #initial request; pre-fill form with the current entry.
        form = ArticleForm(instance=article)
    else:
        form = ArticleForm(instance=article, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('my_blog:posts', args=[posts.id]))
    context = {'posts': posts, 'article': article, 'form': form}
    return render(request, 'posts/edit.html', context)

#to create a signup message in the email
def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
    
        user = User.objects.create_user(
                username = username,
                password = password,
                email = email,
            )
        login(request, user)
        subject = 'welcome to my world'
        message = f"Hi {user.username}, thank you for registering with ibelema's newsletter."
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [user.email,]
        send_mail( subject, message, email_from, recipient_list )
        return redirect('/dashboard/')
    return render(request, 'signup.html')

Documents/my_blog/posts/templates/posts/base.html
<p>
    <a href="{% url 'posts:homepage' %}">Home Page</a>
    <a href="{% url 'posts:posts' %}">Posts</a>
</p>

{% block content %}{% endblock %}

Documents/my_blog/posts/templates/posts/edit.html
{% extends "my_blog/base.html" %}
{% block content %}
    <p><a href="{% url 'my_blog:posts' posts.id %}">{{ posts }}</a></p>
    <p>NewsLetter</p>
    <form action="{% url 'my_blog:edit' article.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>

{% endblock %}

Documents/my_blog/posts/templates/posts/homepage.html
{% extends 'posts/base.html' %}


{% block content %}
    <p>This is the homepage of my very first blog. </p>
    <p>You're welcome, do well to read and give your review</p>

{% endblock %}

Documents/my_blog/posts/templates/posts/new_post.html
{% extends 'posts/base.html' %}

{% block content %}
    <p>Add a new post:</p>
    <form action="{% url 'posts:new_post' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="'submit">add post</button>
    </form>

{% endblock %}

Documents/my_blog/posts/templates/posts/posts.html
{% extends 'posts/base.html' %}

{% block content %}
    <p>POSTS</p>
    <ul>
        {% for post in posts %}
            <li>{{ post }}</li>
        {% empty %}
            <li>No posts have been added. Please hold on</li>
        {% endfor %}
    </ul>

    <a href="{% url 'posts:new_post' %}">Add a new post:</a>
    <a href="{% url 'my_blog:edit' article.id %]">Edit Article></a>

    {% endblock %}